steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/abc-pruebas-479300/cloud-run-source-deploy/changarro-frontend:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/abc-pruebas-479300/cloud-run-source-deploy/changarro-frontend:$COMMIT_SHA']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
  - run
  - deploy
  - changarro-frontend
  - '--image=us-central1-docker.pkg.dev/abc-pruebas-479300/cloud-run-source-deploy/changarro-frontend:$COMMIT_SHA'
  - '--region=us-central1'
  - '--allow-unauthenticated'
  - '--min-instances=0'
  - '--max-instances=3'
  - '--memory=256Mi'
  - '--port=8080'
  - '--project=abc-pruebas-479300'
images:
- 'us-central1-docker.pkg.dev/abc-pruebas-479300/cloud-run-source-deploy/changarro-frontend:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY
